# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Pramis Subedi
email: hello@pramissubedi.com
description: >- # this means to ignore newlines until "baseurl:"
  Thoughts on technology, software development, and life.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pramis.github.io/pramissubedi.github.io" # the base hostname & protocol for your site
icon: /assets/images/icon-512.png
twitter_username: pramissubedi
github_username:  pramissubedi

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

# Disable default GitHub Pages theme
theme: null

# Theme settings
show_excerpts: true
excerpt_length: 25
hide_search: false
hide_credits: false

# GitHub Pages supported plugins
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: "/page/:num/"

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/  
  - vendor/ruby/
  - README.md